# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with: 
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding know host
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: adding env
      run: |
        touch .env
        echo NEXT_PUBLIC_API_URL =${{ secrets.NEXT_PUBLIC_API_URL }} >> .env
        echo NEXT_PUBLIC_HOST_URL =${{ secrets.NEXT_PUBLIC_HOST_URL }} >> .env
        echo NEXT_PUBLIC_DOMAIN =${{ secrets.NEXT_PUBLIC_DOMAIN }} >> .env
        echo NEXT_PUBLIC_WORDPRESS_STORAGE_URL =${{ secrets.NEXT_PUBLIC_WORDPRESS_STORAGE_URL }} >> .env
        echo NEXT_PUBLIC_WORDPRESS_STORAGE_URL_2 =${{ secrets.NEXT_PUBLIC_WORDPRESS_STORAGE_URL_2 }} >> .env
        echo NEXT_PUBLIC_CLOUDINARY_STORAGE_URL =${{ secrets.NEXT_PUBLIC_CLOUDINARY_STORAGE_URL }} >> .env
        echo NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID =${{ secrets.NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID }} >> .env
        
    - run: yarn
    - run: yarn run build --if-present
    - run: rsync -avz .out/ lamesarv@${{ secrets.SSH_HOST }}:/var/www/lamesarv/data/www/test-github-action
  
    
